# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:lints/recommended.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
# linter:
#   rules:
#     - camel_case_types

# see https://dash-overflow.net/articles/getting_started/
#analyzer:
#  strong-mode:
#    implicit-casts: false
    #implicit-dynamic: false
#   exclude:
#     - path/to/excluded/files/**
