name: elec_server
description: An elec server
version: 2.0.2
publish_to: none

environment:
  sdk: ^3.0.2

dependencies:
  actors: ^0.8.4
  archive: ^3.3.7
  args: ^2.1.0
  collection: ^1.15.0
  crypto: ^3.0.2
  csv: ^5.0.1
  dama:
    git: https://github.com/thumbert/dama.git
  date:
    git: https://github.com/thumbert/date.git
  dotenv: ^3.0.0
  elec:
    git: https://github.com/thumbert/elec.git
  grpc: ^3.0.0
  html: ^0.15.1
  http: ^0.13.0
  intl: ^0.18.1
  logging: ^1.0.1
  mongo_dart: ^0.9.1
  more: ^3.0.1
  path: ^1.8.2
  protobuf: ^2.0.0
  puppeteer: ^2.19.0
  shelf: ^1.3.1
  shelf_router: ^1.0.0
  spreadsheet_decoder: ^2.0.0
  table:
    git: https://github.com/thumbert/table.git
  timeseries:
    git: https://github.com/thumbert/timeseries.git
  timezone: ^0.9.2
  tuple: ^2.0.0
  xml: ^6.3.0


dev_dependencies:
  analyzer: ^5.13.0
  build_runner: ^2.4.4
  build_web_compilers: ^4.0.3
  lints: ^2.0.0
  test: ^1.21.0
