name: elec_server
description: An elec server
version: 2.0.2
publish_to: none

environment:
  sdk: ^3.4.3

dependencies:
  actors: ^0.11.0
  archive: ^3.6.0
  args: ^2.5.0
  collection: ^1.15.0
  crypto: ^3.0.2
  csv: ^6.0.0
  dama:
    git: https://github.com/thumbert/dama.git
  date:
    git: https://github.com/thumbert/date.git
  dotenv: ^3.0.0
  duckdb_dart: ^0.2.1
  elec:
    git: https://github.com/thumbert/elec.git
  grpc: ^4.0.0
  html: ^0.15.1
  html_template: ^0.3.0
  http: ^1.2.0
  intl: ^0.18.1
  logging: ^1.0.1
  mongo_dart: ^0.10.3
  more: ^4.0.1
  path: ^1.8.2
  protobuf: ^3.0.0
  puppeteer: ^3.12.0
  shelf: ^1.3.1
  shelf_router: ^1.0.0
  spreadsheet_decoder: ^2.0.0
  table:
    git: https://github.com/thumbert/table.git
  timeseries:
    git: https://github.com/thumbert/timeseries.git
  timezone: ^0.9.2
  tuple: ^2.0.0
  xml: ^6.3.0


dev_dependencies:
  analyzer: ^6.5.0
  build_runner: ^2.4.11
  build_web_compilers: ^4.0.3
  lints: ^4.0.0
  test: ^1.21.0
