name: elec_server
description: A web server built using the shelf package.
version: 0.0.1
#homepage: https://www.example.com
#author: tony humbert <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  args: ^0.13.7
  dart_to_js_script_rewriter: ^1.0.1
  date:
      git:
          url: git://github.com/thumbert/date.git
  elec:
        git:
            url: git://github.com/thumbert/elec.git
  func: 1.0.0
  intl: '>=0.14.0 <0.16.0'
  logging: '>=0.11.2 <0.12.0'
  logging_handlers: ">=0.8.0 <0.9.0"
  mongo_dart: 0.3.0
  more: ^1.8.1
  rpc: ^0.5.7+1
  spreadsheet_decoder: 0.3.2
  table:
        git:
            url: git://github.com/thumbert/table.git
  timezone: '>=0.4.3 <0.5.0'
  tuple: '>=1.0.0 <2.0.0'


dev_dependencies:
  browser: ^0.10.0
  test: ^0.12.0

transformers:
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
