name: elec_server
description: A web server built using the shelf package.
version: 1.0.0
#homepage: https://www.example.com
author: Tony Humbert <tony.humberts@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  args: ^1.5.0
#  dart_to_js_script_rewriter: ^1.0.1
  date:
      git:
          url: git://github.com/thumbert/date.git
  elec:
        git:
            url: git://github.com/thumbert/elec.git
  intl: '>=0.14.0 <0.16.0'
  mongo_dart: 0.3.3
  more: ^1.10.1
  rpc: ^0.6.0
  spreadsheet_decoder: 1.0.0
  table:
        git:
            url: git://github.com/thumbert/table.git
  timezone: ^0.5.0-dev-3
  tuple: '>=1.0.0 <2.0.0'


dev_dependencies:
#  browser: ^0.10.0
  test: '>=1.3.0'

#transformers:
#- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
