name: elec_server
description: An elec server
version: 1.0.0
#homepage: https://www.example.com
author: Tony Humbert <tony.humberts@gmail.com>


environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.0
  collection: '>=1.14.11 <2.0.0'
  date:
    git:
      url: git://github.com/thumbert/date.git
  dotenv: '>=2.0.0 <3.0.0'
  elec:
    git:
      url: git://github.com/thumbert/elec.git
  grpc: '>=1.0.0 <2.0.0'
  html: '>=0.13.0 <1.0.0'
  intl: '>=0.14.0 <1.0.0'
  jexcel_dart:
    git:
      url: git://github.com/thumbert/jexcel-dart.git
  logging: '>=0.11.3+2 <1.0.0'
  mongo_dart: '>=0.3.6 <1.0.0'
  more: '>=1.10.1 <2.0.0'
  protobuf: '>=0.14.3 <1.0.0'
  rpc: '>=0.6.0 <1.0.0'
  spreadsheet_decoder: '>=1.2.0 <2.0.0'
  table:
    git:
      url: git://github.com/thumbert/table.git
  timezone: '>=0.5.5 <1.0.0'
  tuple: '>=1.0.0 <2.0.0'


dev_dependencies:
  analyzer: '>=0.39.1 <1.0.0'
  build_runner: '>=1.7.2 <2.0.0'
  build_web_compilers: '>=2.7.2 <3.0.0'
  pedantic: ^1.9.2
  test: '>= 1.15.2 <2.0.0'
