name: elec_server
description: An elec server
version: 2.0.0
author: Tony Humbert <tony.humberts@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  collection: ^1.15.0
  date:
    git:
      url: git://github.com/thumbert/date.git
  dotenv: ^3.0.0
  elec:
    git:
      url: git://github.com/thumbert/elec.git
  grpc: ^3.0.0
  html: ^0.15.0
  intl: ^0.17.0
#  jexcel_dart:
#    git:
#      url: git://github.com/thumbert/jexcel-dart.git
  logging: ^1.0.1
  mongo_dart: ^0.7.0+1
  more: ^3.0.1
  protobuf: ^2.0.0
  shelf_router: ^1.0.0
  spreadsheet_decoder: ^2.0.0
  table:
    git:
      url: git://github.com/thumbert/table.git
  timezone: ^0.7.0
  tuple: ^2.0.0


dev_dependencies:
  analyzer: ^1.5.0
  build_runner: ^2.0.3
  build_web_compilers: ^3.0.0
  pedantic: ^1.11.0
  test: ^1.17.4
